# Generated by Django 4.0.6 on 2022-08-01 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_rename_notes_carddata_cc_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carddata',
            name='exp_date',
            field=models.CharField(max_length=200, verbose_name='Expiry Date'),
        ),
    ]
