# Generated by Django 4.0.6 on 2022-08-01 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_carddata_exp_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carddata',
            name='cc_number',
            field=models.CharField(max_length=16, verbose_name='Card Number'),
        ),
        migrations.AlterField(
            model_name='carddata',
            name='ccv_code',
            field=models.CharField(max_length=3, verbose_name='CCV/Security Code'),
        ),
    ]
