# Generated by Django 4.0.6 on 2022-08-02 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_carddata_cc_number_alter_carddata_ccv_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='carddata',
            name='delete_card',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='generalpassword',
            name='delete_pass',
            field=models.BooleanField(default=False),
        ),
    ]
